---
- name: Pull MySQL Docker image on remote host
  hosts: db_servers
  become: yes
  tasks:
    - name: Install pip3
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install Docker SDK for Python
      pip:
        name: docker
        executable: pip3

    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Pull MySQL Docker image
      community.docker.docker_image:
        name: mysql
        tag: latest
        source: pull
